import {
  CalendarDays,
  Home,
  Users,
  FileText,
  Briefcase,
  DollarSign,
  Megaphone,
  BarChart,
  Clock,
  Gift,
  Plus,
  ScrollText,
  Download,
  Image,
  UserPlus,
} from "lucide-react";

export const menuItems = [
  { icon: Plus, label: "Create" },
  { icon: Home, label: "Home" },
  { icon: CalendarDays, label: "Schedule" },
  { icon: UserPlus, label: "Leads", path: "/" },
  { icon: Users, label: "Clients" },
  { icon: Download, label: "Requests" },
  { icon: ScrollText, label: "Quotes" },
  { icon: Briefcase, label: "Jobs" },
  { icon: DollarSign, label: "Invoices" },
  { icon: Megaphone, label: "Marketing" },
  { icon: BarChart, label: "Reports" },
  { icon: Image, label: "Expenses" },
  { icon: Clock, label: "Timesheets" },
  { icon: Gift, label: "Refer a Friend" },
];